### ISSUE TITLE
verify_hash/3 breaks phauxth

### ISSUE THREAD

**Issue by dsignr** [riverrun/bcrypt_elixir#1]
W.R.T: 1b00fa78e0393bfcd1f02861d59dfef518df1c58

This breaks Phauxth with `function Bcrypt.verify_hash/3 is undefined or private.`

**Comment by riverrun** [comment]
It's now Bcrypt.verify_pass/2 -- sorry about the confusion :)

**Comment by dsignr** [comment]
Ok, thanks for the clarification. Upgrading to Phauxth 0.12.1-rc.1 solves this for now. Closing and thank you :)
