### ISSUE TITLE
module Bcrypt.Base is not available on Windows

### ISSUE THREAD

**Issue by philippneugebauer** [riverrun/bcrypt_elixir#11]
I hope that's the right repo for the issue.

I tried compiling `bcrypt_elixi`r on Windows and after it failed, I managed to compile `bcrypt` through the installation of nmake by VS.

Although the compilation works now, I still get following error when `bcrypt` is called (or similar):
```
function Bcrypt.Base.gensalt_nif/3 is undefined (module Bcrypt.Base is not available)
```

The console output is splitted in two parts:
```
iex(1)> [error] Process #PID<0.1019.0> raised an exception
** (RuntimeError) An error occurred when loading Bcrypt.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use version 0.12 of bcrypt_elixir.
See the Comeonin wiki for more information.

    lib/bcrypt/base.ex:14: Bcrypt.Base.init/0
    (kernel) code_server.erl:1333: anonymous fn/1 in :code_server.handle_on_load/5
iex(1)> [warn] The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{message: "An error occurred when loading Bcrypt.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse version 0.12 of bcrypt_elixir.\nSee the Comeonin wiki for more information.\n"},
 [{Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 14]},
  {:code_server, :"-handle_on_load/5-fun-0-", 1,
   [file: 'code_server.erl', line: 1333]}]}
```

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Bcrypt.Base.gensalt_nif/3 is undefined (module Bcrypt.Base is not available)
        Bcrypt.Base.gensalt_nif([169, 27, 153, 198, 249, 251, 88, 148, 167, 68, 229, 90, 49, 45, 22, 248], 12, 98)
        lib/bcrypt.ex:52: Bcrypt.gen_salt/2
        lib/bcrypt.ex:85: Bcrypt.hash_pwd_salt/2
```

I have Erlang with OTP 20 and nmake installed, so I have no idea what I am doing wrong:
```
1> erlang:system_info(otp_release).
"20"
```

Elixir:
```
>iex
Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)
```

I compiled `bcrypt` by following this answer: https://social.msdn.microsoft.com/Forums/en-US/e56b3e76-08f4-422c-913e-df729eebfe7a/vs2017nmake-is-not-recongnizing-in-command-prompt?forum=msbuild

**Comment by riverrun** [comment]
Did you compile bcrypt with mix compile (or mix deps.compile) after installing nmake and setting the environment variables?

**Comment by philippneugebauer** [comment]
yeah, I executed the following commands:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat
cmd /K "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd\ext\vcvars.bat" amd64
>mix deps.compile
```

The following is the output of mix deps.compile:
```
==> base64url (compile)
===> Compiling mimerl
===> Compiling metrics
==> fs (compile)
===> Compiling unicode_util_compat
===> Compiling idna
===> Compiling ranch
==> poolboy (compile)
warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
  c:/Users/ppn/SportsConnected/deps/gravity/mix.exs:10

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  c:/Users/ppn/SportsConnected/deps/gravity/mix.exs:11

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  c:/Users/ppn/SportsConnected/deps/gravity/mix.exs:12

warning: String.strip/1 is deprecated, use String.trim/1
  c:/Users/ppn/SportsConnected/deps/poison/mix.exs:4

==> ssl_verify_fun (compile)
==> bcrypt_elixir

Microsoft (R) Program Maintenance Utility Version 14.12.25834.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        del /Q /F priv
        erl -eval "io:format(\"~s~n\", [lists:concat([\"ERTS_INCLUDE_PATH=\", code:root_dir(), \"/erts-\", erlang:system_info(version), \"/include\"])])" -s init stop -noshell > Makefile.auto.win
        nmake /                   /F Makefile.win priv\bcrypt_nif.dll

Microsoft (R) Program Maintenance Utility Version 14.12.25834.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        if NOT EXIST "priv" mkdir "priv"
        cl /O2 /EHsc /I"c_src" /I"c:/Program Files/erl9.1/erts-9.1/include" /LD /MD /Fepriv\bcrypt_nif.dll  c_src\bcrypt_nif.c c_src\blowfish.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25834 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

bcrypt_nif.c
blowfish.c
Generating Code...
Microsoft (R) Incremental Linker Version 14.12.25834.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/dll
/implib:priv\bcrypt_nif.lib
/out:priv\bcrypt_nif.dll
bcrypt_nif.obj
blowfish.obj
   Creating library priv\bcrypt_nif.lib and object priv\bcrypt_nif.exp
===> Compiling certifi
===> Compiling hackney
===> Compiling cowlib
src/cow_multipart.erl:392: Warning: call to crypto:rand_bytes/1 will fail, since it was removed in 20.0; use crypto:strong_rand_bytes/1

===> Compiling cowboy
==> ecto
Compiling 1 file (.ex)
```

**Comment by riverrun** [comment]
I'll look into it further and get back to you as soon as I can.

**Comment by riverrun** [comment]
Just to clarify your situation, I have a few further questions (before looking at these questions, try deleting the `_build` directory in the main application folder and running your tests again - sometimes this works :) ):

* do you have one version of Erlang, or many versions, installed?
* are you running the tests from within Visual Studio or within a cmd shell (or powershell)?
    * are you using a single window or multiple windows?

**Comment by riverrun** [comment]
Ok. There are some suggestions on https://github.com/riverrun/comeonin/issues/52 and https://github.com/riverrun/comeonin/issues/95

Could you try them and let me know how you get on.

**Comment by philippneugebauer** [comment]
yeah, I was pretty much trying already all of these fixes, but they did not help.
The interesting thing is, that I can compile the code without errors and the error just shows up, when I call the library which seems to be differently for the other problems

**Comment by philippneugebauer** [comment]
The only difference I found was that I used the current version of VS, so of 2017. I am not pretty sure, but do you think this could be a problem? On the other hand, my problem looks different to the other ones reported for me

**Comment by riverrun** [comment]
I might be able to test this on Windows within the next couple of days. I'll keep you informed.

**Comment by acidhorse** [comment]
Same issue, any pointers?

**Comment by riverrun** [comment]
Hopefully, I'll have some time this weekend to look at it.

**Comment by philippneugebauer** [comment]
I got the same issue with the integrated ubuntu and realized I needed to install Bcrypt. While it fixed it on linux, I still haven't got it working on Windows.

**Comment by riverrun** [comment]
@philippneugebauer @osazemeu @acidhorse are you all using Visual Studio 2017? And could you let me know what error messages you are getting?

**Comment by Camilonicolas** [comment]
@riverrun I have the same issue. I'm working with VS 14.0 (because I can't compile Comeonin with VS 2017, don't know why). Only when I try to use the function "Comeonin.Bcrypt.hashpwsalt(pass)" the error appears, but I can compile the proyect without any problem. 
I'm using {:bcrypt_elixir, "~> 0.12"} with Erlan OTP 19 on windows. 

This Error appears on my page when I try tp create a User (the problem is with the password):
"**Function Comeonin.Bcrypt.hashpwsalt/1 is undefined (module Comeonin.Bcrypt is not available)**"

**\web\models\user.ex**

`defmodule Evidencia2.User do
	use Evidencia2.Web, :model
		schema "users" do
		field :name, :string
		field :username, :string
		field :password, :string, virtual: true
		field :password_hash, :string 

		timestamps()
	end
	def changeset(model, params \\ :empty) do
		model
		|> cast(params, ~w(name username), [])
		|> validate_length(:username, min: 1, max: 20)
	end

	def registration_changeset(model, params) do
		model
		|> changeset(params)
		|> cast(params, ~w(password), [])
		|> validate_length(:password, min: 6, max: 100)
		|> put_pass_hash()
	end

	defp put_pass_hash(changeset) do
		case changeset do
			%Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
			put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
			_ ->
			changeset
		end
	end
end
`

**Comment by acidhorse** [comment]
@riverrun - for my 2 cents, same issue for me as @Camilonicolas has.

'module Comeonin.Bcrypt is not available'

@Camilonicolas - you might be able to compile using the VS2017 'Developer Command Prompt'?  It was the only thing that worked for me in the end.

**Comment by Camilonicolas** [comment]
@riverrun I just unninstall everything related with Visual Studio and reinstalled everything again. I selected each of the installation boxes (more than 80GB of installation) and that worked for me. Maybe I had something wrong installed, I don't know, but it solved my problem.

@acidhorse  I was using the Developer Command Prompt before, but I had the same issue.

Now I'm using "Visual C++ 2015 x86 x64 Cross Build Tools Command Prompt" that is in "C:\Program Files (x86)\Microsoft Visual C++ Build Tools" (if someone don't know how to find it.)

**Comment by riverrun** [comment]
Does anyone have any updates on setting up the C environment on Windows? If you do, please let me know.

**Comment by olivermt** [comment]
I am getting the same error with VS 2017 as reported above.

Do you have any more ideas of what to do in terms of getting you more debugging information?

I could spin up a VM in azure, reproduce and give you access if that makes it easier.

**Comment by riverrun** [comment]
What version of bcrypt_elixir are you using? Could you also just print out the error you are getting?

**Comment by olivermt** [comment]
````
iex(2)> Bcrypt.Base.hashpwd
[error]  Process #PID<0.1452.0> raised an exception
** (RuntimeError) An error occurred when loading Bcrypt.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use version 0.12 of bcrypt_elixir.
See the Comeonin wiki for more information.

    (bcrypt_elixir) lib/bcrypt/base.ex:17: Bcrypt.Base.init/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
[warn]  The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{message: "An error occurred when loading Bcrypt.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse version 0.12 of bcrypt_elixir.\nSee the Comeonin wiki for more information.\n"}, [{Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 17]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', line: 1340]}]}

[error]  Process #PID<0.1454.0> raised an exception
** (RuntimeError) An error occurred when loading Bcrypt.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use version 0.12 of bcrypt_elixir.
See the Comeonin wiki for more information.

    (bcrypt_elixir) lib/bcrypt/base.ex:17: Bcrypt.Base.init/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
[warn]  The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{message: "An error occurred when loading Bcrypt.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse version 0.12 of bcrypt_elixir.\nSee the Comeonin wiki for more information.\n"}, [{Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 17]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', line: 1340]}]}

** (UndefinedFunctionError) function Bcrypt.Base.hashpwd/0 is undefined (module Bcrypt.Base is not available)
    (bcrypt_elixir) Bcrypt.Base.hashpwd()
```
This is with 2.0 and using

```
*********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
```

Compiling seems fine:
```
C:\Users\olive\Documents\code\safari\api>mix deps.compile comeonin
==> comeonin
Compiling 4 files (.ex)
Generated comeonin app

C:\Users\olive\Documents\code\safari\api>mix deps.compile bcrypt_elixir
==> bcrypt_elixir

Microsoft (R) Program Maintenance Utility Version 14.16.27026.1
Copyright (C) Microsoft Corporation.  All rights reserved.

        del /Q /F priv
        erl -eval "io:format(\"~s~n\", [lists:concat([\"ERTS_INCLUDE_PATH=\", code:root_dir(), \"/erts-\", erlang:system_info(version), \"/include\"])])" -s init stop -noshell > Makefile.auto.win
        nmake /                   /F Makefile.win priv\bcrypt_nif.dll

Microsoft (R) Program Maintenance Utility Version 14.16.27026.1
Copyright (C) Microsoft Corporation.  All rights reserved.

        if NOT EXIST "priv" mkdir "priv"
        cl /O2 /EHsc /I"c_src" /I"c:/Program Files/erl10.1/erts-10.1/include" /LD /MD /Fepriv\bcrypt_nif.dll  c_src\bcrypt_nif.c c_src\blowfish.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

bcrypt_nif.c
blowfish.c
Generating Code...
Microsoft (R) Incremental Linker Version 14.16.27026.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/dll
/implib:priv\bcrypt_nif.lib
/out:priv\bcrypt_nif.dll
bcrypt_nif.obj
blowfish.obj
   Creating library priv\bcrypt_nif.lib and object priv\bcrypt_nif.exp
Compiling 3 files (.ex)
Generated bcrypt_elixir app
```

Nmake:

```
C:\Users\olive\Documents\code>nmake

Microsoft (R) Program Maintenance Utility Version 14.16.27026.1
Copyright (C) Microsoft Corporation.  All rights reserved.
```

I suspect this maybe has to do with newer versions of OTP and how they load nifs, because I have heard people experience this exact bug with Argon2 as well.

**Comment by olivermt** [comment]
Also:

```C:\Users\olive\Documents\code\safari\api>elixir -v
Erlang/OTP 21 [erts-10.1] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.8.1 (compiled with Erlang/OTP 20)
```

**Comment by riverrun** [comment]
Could you open a shell normally (without running vcvarsall.bat command) and try the following?

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

Then try compiling Bcrypt and running it.

Then open another shell normally and run this command:

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd" -arch=x64

Again, try compiling Bcrypt and running it.

Let me know how you get on.

**Comment by olivermt** [comment]
It worked with the arch flag! Nice, thank you VERY much.. no more iex in wsl fighting with vscode in windows about file ownership when using elixirls :)

**Comment by riverrun** [comment]
Glad to hear it worked. I will update the documentation and wiki to make them up-to-date.

**Comment by Erfan1995** [comment]
@riverrun Thanks for providing the solution. Your solution works in 2024 even.

**Comment by anatoliykmetyuk** [comment]
The fix didn't work for me. Still getting "An error occurred when loading Bcrypt.\nMake sure you have a C compiler and Erlang 20 installed".

**Comment by Artyees** [comment]
i was sorting this issue for almost 3 days and the given solution worked, Thanks
