### ISSUE TITLE
[Help] bcrypt on docker container?

### ISSUE THREAD

**Issue by eaguilera23** [riverrun/bcrypt_elixir#15]
Hi guys. I'm trying to run my elixir project on docker, and it says that I need a C compiler and Erlang 20.

I am using the image `elixir:1.6.6` which uses the image `erlang:21`.

When I run `erl` it shows

```
Erlang/OTP 20 [erts-9.3.3.3] [source] [64-bit] [smp:4:4] [ds:4:4:10]...
```

And I run apt-get install gcc, it shows:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc is already the newest version (4:6.3.0-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

The same with `make` and `libc6-dev`

Basically the error at runtime (and starting) is:

```
The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{message: "An error occurred when loading Bcrypt.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use version 0.12 of bcrypt_elixir.
See the Comeonin wiki for more information.
"},
[{Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 17]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', line: 1340]}]}
```

Have you run bcrypt as dependency on a docker container?

Thanks in advance.

**Comment by izelnakri** [comment]
Same issue here, my docker container runs archlinux with gcc compiler and Erlang/OTP 21 so this issue is super weird. Downgraded the dependency to 0.12 and its working, the latest version works on my local MacOS but not in docker.

**Comment by izelnakri** [comment]
@eaguilera23 I figured I missed .dockerignore file in my backend directory, which meant my mac os _build folder was in my archlinux container!

**Comment by eaguilera23** [comment]
@izelnakri What worked for me was to compile the dependencies on the container as part of the docker file.

As I understood, is that the NIF need to be compile on the computer that's going to be used. Good that you got it working too 👍

**Comment by ryo33** [comment]
The reason for this issue is that bcrypt_elixir place the NIF artifacts into `deps`, not `_build`
## Reproduce
1. `mix compile`
2. `rm deps/bcrypt_elixir/priv/bcrypt_nif.so`
## Ways to resolve the situation
### Copy the NIF artifacts
* `COPY deps/bcrypt_elixir/priv/bcrypt_nif.so `
### Force compile
* `RUN mix deps.compile --force bcrypt_elixir`

**Comment by davidalencar** [comment]
This worked for me:

`mix deps.compile --force bcrypt_elixir`

Thanks @ryo33
