### ISSUE TITLE
function Bcrypt.Base.gensalt_nif/3 is undefined on OSX Sierra

### ISSUE THREAD

**Issue by mogadget** [riverrun/bcrypt_elixir#19]
Im running Elixir 1.8, Erlang 21 on OSX and Im getting an error `function Bcrypt.Base.gensalt_nif/3 is undefined (module Bcrypt.Base is not available)`.  

I tried various ways to delete /deps and /_build directory and mix deps.get but no avail.   Anybody experienced this before?

**Comment by riverrun** [comment]
First, a couple of questions:

* is `bcrypt_elixir` listed in the `deps` section of the mix.exs file?
* what command are you running when you get this error?

**Comment by mogadget** [comment]
I found the solution, it something to do with compiling that creates bcrypt_nif.so.  For some reason, the C compiler was not able to generate the .so file properly and therefore it's failing to load.  My solution is I upgraded my OSX and all works fine now.

**Comment by tarasyarema** [comment]
I have the same issue now with Sonoma 14.1.2, with bcrypt version 3.0 in the mix deps, and 

```
Erlang/OTP 24 [erts-12.3.2.14] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```

giving me this error

```
     ** (UndefinedFunctionError) function Bcrypt.Base.gen_salt/2 is undefined (module Bcrypt.Base is not available)
     stacktrace:
       (bcrypt_elixir 3.1.0) Bcrypt.Base.gen_salt(12, false)
       (bcrypt_elixir 3.1.0) lib/bcrypt.ex:77: Bcrypt.hash_pwd_salt/2
       (bcrypt_elixir 3.1.0) lib/bcrypt.ex:46: Bcrypt.add_hash/2
```

**Comment by tarasyarema** [comment]
Ok, after hacking a bit the `load_nif` call, the error is the following

```
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(.../_build/dev/lib/bcrypt_elixir/priv/bcrypt_nif.so, 0x0002): tried: \'/Users/2pac/.../_build/dev/lib/bcrypt_elixir/priv/bcrypt_nif.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64\')), \'/System/Volumes/Preboot/Cryptexes/OS/Users/2pac/.../_build/dev/lib/bcrypt_elixir/priv/bcrypt_nif.so\' (no such file), \'/Users/2pac/.../_build/dev/lib/bcrypt_elixir/priv/bcrypt_nif.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64\'))\''}}
```

**Comment by riverrun** [comment]
@tarasyarema please ask about this at https://elixirforum.com/ You are more likely to get help from developers using the same architecture, and perhaps facing the same issue.
