### ISSUE TITLE
Document breaking changes for 1.1.1 -> 2.0.0

### ISSUE THREAD

**Issue by lpil** [riverrun/bcrypt_elixir#20]
Hello! I see the major version number has been incremented, meaning that there has been a breaking change in the library.

From reading the source code I am unable to determine what the breaking change is, could it be documented please? :)

Thanks,
Louis

**Comment by riverrun** [comment]
Yes, I need to publicize the changes a bit more. The moduledocs for the Bcrypt module and the [Comeonin README](https://github.com/riverrun/comeonin) will give you more information. The main change is that comeonin is now a dependency of bcrypt_elixir, and comeonin defines two behaviours that bcrypt_elixir implements.

**Comment by lpil** [comment]
Thank you!:)
