### ISSUE TITLE
Does not verify hashes created by another Bcrypt library

### ISSUE THREAD

**Issue by shituser** [riverrun/bcrypt_elixir#25]
I have a legacy PHP project, which I recently started rewriting in Elixir. I noticed that the library does not verify password hashes, generated by the PHP app, whereas the PHP app is able to verify hashes, generated by bcrypt_elixir.

It seems that the PHP app is generating hashes starting with `$2y$10$`, whereas the Elixir ones start with `$2b$12$`. Once I change the `$2y$` into `$2b$`, I can verify php hashes in Elixir.

Example:
`php> Hash::make("Example");`
`php> $2y$10$remMqr6.VRFfGJT3Xtpumu1ql2GXRjrf.5McFBGyQb4GV1p4KsN3m`

`iex> Bcrypt.verify_pass("Example", "$2y$10$remMqr6.VRFfGJT3Xtpumu1ql2GXRjrf.5McFBGyQb4GV1p4KsN3m")`
`iex> false`
BUT
`iex> Bcrypt.verify_pass("Example", "$2b$10$remMqr6.VRFfGJT3Xtpumu1ql2GXRjrf.5McFBGyQb4GV1p4KsN3m")`
`iex> true`

**Comment by riverrun** [comment]
This has come up before - see [this issue](https://github.com/riverrun/comeonin/issues/103) and [this note on the Comeonin wiki](https://github.com/riverrun/comeonin/wiki/Choosing-the-password-hashing-library) (under Bcrypt versions), but I should really add a note to the README for this repository as well.

Long story short, the '2y' prefix should be compatible with the '2b' prefix, and changing '2y' to '2b' should enable you to verify these hashes.

I will also look into maybe supporting the '2y' prefix.

**Comment by shituser** [comment]
Thanks for the reply, I should have probably read the Comeonin documentation before submitting this.

**Comment by riverrun** [comment]
Thanks for raising the issue - it's good to know when the documentation isn't so clear. I have just updated the README with a note about prefixes and compatibility with other libraries.
