### ISSUE TITLE
Why is this argument error?

### ISSUE THREAD

**Issue by tomekowal** [riverrun/bcrypt_elixir#27]
```
** (ArgumentError) argument error
    stacktrace:
       (bcrypt_elixir) Bcrypt.Base.hash_nif([189, 75, 138, 198, 227, 203, 117, 13, 103, 23, 113, 66, 153, 149, 226, 67, 31, 101, 36, 61, 167, 103, 186, 101, 36, 88, 119, 103, 96, 112, 235, 75], [0, 50, 98, 36, 48, 52, 36, 71, 72, 56, 65, 122, 75, 51, 87, 77, 103, 117, 54, 78, 87, 53, 89, 101, 102, 84, 106, 115, 101])
```

Hi, I encountered the strange behaviour that I can't explain.
This error popped up in tests with randomly generated input.
Calling it with those values reproduces the error.

(we are using version bcrypt 1.0.7)

The exact code we are running that sometimes produces the issue is:

```
:crypto.strong_rand_bytes(32)
|> Comeonin.Bcrypt.hashpwsalt()
```

Thanks for the fantastic library ❤️

**Comment by riverrun** [comment]
Using a newer version of Bcrypt, I can't replicate this issue. Could you try updating Bcrypt and seeing if that solves the problem?

To update Bcrypt, follow these steps:

* in the `mix.exs` file's `deps` section, remove the `comeonin` dependency and change the `bcrypt` version to 2.2
* change all references to `Comeonin.Bcrypt.hashpwsalt` to `Bcrypt.hash_pwd_salt`
* change all references to `Comeonin.Bcrypt.checkpw` to `Bcrypt.verify_pass`

**Comment by tomekowal** [comment]
Thank you! That worked.
The bug was in a salting function. It was fixed in this commit https://github.com/riverrun/bcrypt_elixir/commit/1443bd45ccf72d83dbc0e7f547a297bd02d35299 so upgrading worked.
