### ISSUE TITLE
Set unusable password

### ISSUE THREAD

**Issue by spapas** [riverrun/bcrypt_elixir#38]
Hello! Is there a string I could save on my password field so as to have an unusable password ? I've got some users that are able to login through a different method and I don't want them to be able to login with a password.

**Comment by brettinternet** [comment]
How about a random strong password? Would this work?

```
:crypto.strong_rand_bytes(32)
|>  Bcrypt.hash_pwd_salt()
```

**Comment by riverrun** [comment]
Closing this issue. If anyone feels like reopening, please let me know.
