### ISSUE TITLE
Broken "go to code" links in docs

### ISSUE THREAD

**Issue by chukinas** [riverrun/bcrypt_elixir#43]
When I click any of the `</>` links in the https://hexdocs.pm/bcrypt_elixir/3.0.1 docs, I get a 404  on github.

Example: When on https://hexdocs.pm/bcrypt_elixir/3.0.1/Bcrypt.html, when I click the `</>`, I go to https://github.com/riverrun/bcrypt_elixir/blob/v3.0.1/lib/bcrypt.ex#L1 and see a github 404 message.

I'll gladly take a stab at fixing this for you if you're open to contributions.

**Comment by riverrun** [comment]
Later this week I will try updating the dependencies and see if that fixes this. Thanks for reporting the issue.

**Comment by josevalim** [comment]
@riverrun it seems you forgot the git tag. If you go to the commit you released v3.0.1, do a `git tag v3.0.1`, and `git push --tags`, you should be good!

If you have some time, it may be worth also doing `mix deps.update ex_doc` and `mix hex.publish docs` on main/master, to use the latest ExDoc version :) (v0.30.5). :)

**Comment by riverrun** [comment]
I just updated the dependencies and released version 3.1.0 - and remembered to add a git tag.
